### PR TITLE
Chat feature in theme

### PR DESCRIPTION
**Pull request by Xoeseko**
Hey Jonathan this is the contribution we were talking about yesterday sorry it took so long just for these couple of lines... With this layout you should be able to use the slate theme with the chat without using posts but maybe make separate pages for documentation (If we want them counted on the market) I hope this works for you ? Tell me if you need help to flesh out the documentation ?

### CODE REVIEW

**Review by JonDavMartin — COMMENTED** [review]
Ok thank you very much! I am actually now planning to show the students how to use posts like you showed me yesterday; I'll incorporate an explanation in the readme of the "Gitumentation" repository. Is it still possible to use posts after your changes ? If yes then I'll merge your pull request

**Comment by Xoeseko** [comment]
Hmm yes although I am not sure it was ever possible with the slate theme did you test it out ?

#### EDIT:
My bad I forgot we changed to jekyll-theme-minimal which fully supports pages I changed the base layout while leaving the chat feature on..

**Comment by JonDavMartin** [comment]
> Hmm yes although I am not sure it was ever possible with the slate theme did you test it out ?

I just created a "Post" in your branch. Looks like working but I don't know if it'll be displayed on the webpage. If it doesn't then we can maybe forget about the slate theme and just change themes.

**Comment by Xoeseko** [comment]
You can forget about the chat branch it does not work. I forgot but branch management doesn't come with the default rights... You can actually delete it I can't do that either. The current pull request is from the branch in my repo since I have more control on the work there

**Comment by Xoeseko** [comment]
Did you close without merging?

**Pull request merged**
